=head1 NAME

guprecords - Global uptime records

Shows uprecord stats of several hosts at once.

=head2 Synopsis

guprecords [--help] [--total|--all] [--count=i] [--indir=s]

=head2 Parameters

=over

=item --all

Shows every individual uptime of all hosts.

=item --count=i

Show i num of entries. Default is 23.

=item --nofqdn

Don't display the FQDNs

=item --help

Shows the help

=item --indir=s

Read all the *.records files from dir s. Default is ./

=item --total

Aggregates a total uptime for every single host.

=back


=head2 Quick getting started

=head3 Uptimed

Firstival, you need to collect uprecords using the uptimed deaemon. To install it run:

    sudo aptitude install uptimed

Please consult the L<uptimed> and L<uprecords> manpages. Please ensure to understand how it works and what it does.

uptimed collects uprecords to 

  /var/spool/uptimed/records

And this file is used by guprecords for further processing.

=head3 Collect all the uprecords

You may have several hosts with uptimed running already. Collect all the records file to a central repository (e.g. git).  Name each file FQDN.records and run

  guprecords --indir ./

You may automate the collecting of all the uprecords using something like cron or puppet.

=head1 LICENSE

See package description or project website.

=head1 AUTHOR

Paul Buetow - <http://buetow.org>

=cut
